name: Production Image Push

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .internal/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/prod:latest,ghcr.io/${{ github.repository }}/prod:${{ github.sha }}
